/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex33;

import org.testng.annotations.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import static org.testng.AssertJUnit.assertEquals;

public class AppTest {

    public static final Tree<T> arbre0() {
        return new Node(new ArrayList<Tree<T>>());
    }

    public static final Tree<Integer> arbre1() {
        final Tree<Integer> f1 = new Leaf<>(1);
        final Tree<Integer> f2 = new Leaf<>(2);
        final Tree<Integer> n1 = new Node<>(List.of(f1,f2));
        final Tree<Integer> f3 = new Leaf<>(3);
        final Tree<Integer> n2 = new Node<>(List.of(n1,f3));
        return n2;
    }

    public static final Tree<String> arbre2() {
        final Tree<String> f1 = new Leaf<>("2");
        final Tree<String> f2 = new Leaf<>("3");
        final Tree<String> n1 = new Node<>(List.of(f1,f2));
        final Tree<String> f3 = new Leaf<>("1");
        final Tree<String> n2 = new Node<>(List.of(n1,f3));
        return n2;
    }

    public static final Tree<Float> arbre3() {
        final Tree<Float> f1 = new Leaf<>(2.5f);
        final Tree<Float> f2 = new Leaf<>(1.5f);
        final Tree<Float> n1 = new Node<>(List.of(f1,f2));
        final Tree<Float> f3 = new Leaf<>(3.5f);
        final Tree<Float> n2 = new Node<>(List.of(n1,f3));
        return n2;
    }

    @Test public void testSize() {
        assertEquals(0, arbre0().size());
        assertEquals(3, arbre1().size());
        assertEquals(3, arbre2().size());
        assertEquals(3, arbre3().size());
    }


    @Test public void testValeurs() {
        final Set<Integer> contenu = Set.of(1,2,3);
        assertEquals(Set.of(), arbre0().values());
        assertEquals(contenu, arbre1().values());
        assertEquals(contenu, arbre2().values());
        assertEquals(contenu, arbre3().values());
    }

}
